### PR TITLE
NXP-25646: add support to detect unsafe content with AWS Rekognition

### PR DESCRIPTION
**Pull request by mcedica**

### CODE REVIEW

**Comment by covolution** [comment]
Do you have a test for this?

**Comment by mcedica** [comment]
no, but there is no test actually invoking the providers in the addon in the first place

**Review by glefevre — APPROVED** [review]

**Comment by mcedica** [comment]
@covolution I think we should not upload an unsafe image in the end in our sources :) just to see if rekognition adds the right tags :)

**Review by covolution — COMMENTED** [review]
:+1: 
Assuming you have manually tested it.

**Comment by PedroCardoso** [comment]
@mcedica You would not be testing the model accuracy, but the API call. Put any "safe" picture and check the result is that the picture is safe.

**Pull request merged**
